using System.Reflection;
using System.Text;
using Currency.Reference.Iso4217.Generators.Factories;
using Currency.Reference.Iso4217.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Currency.Reference.Iso4217.Generators;

public abstract class BaseIncrementalGenerator : IIncrementalGenerator
{
    public virtual string HintName { get; } = string.Empty;
    protected const string DefaultNamespace = "Currency.Reference.Iso4217";
    protected const string DiagnosticsTitle = "Generator error";
    protected const string ErrorMark = "__ERROR__";
    protected const string GeneratorName = "Currency.Reference.Iso4217.Generators source generator";
    protected readonly ErrorFactory ErrorFactory = new();
    public abstract void Initialize(IncrementalGeneratorInitializationContext context);

    protected void AddStubIfErrors(SourceProductionContext spc, string hintName, string stubSource, GeneratorType type)
    {
        if (!ErrorFactory.IsExists()) return;
        ErrorFactory.ShowDiagnostics(spc, type);
        spc.AddSource(hintName, SourceText.From(stubSource, Encoding.UTF8));
    }

    protected static (string original, string replacement, string historical) LoadJsonResources(Assembly assembly)
    {
        string ReadResource(string name)
        {
            using var stream = assembly.GetManifestResourceStream(name)
                               ?? throw new InvalidOperationException($"{name} not found.");
            using var reader = new StreamReader(stream, Encoding.UTF8);
            return reader.ReadToEnd();
        }

        return (
            ReadResource("Currency.Reference.Iso4217.Generators.Content.list-original-currencies.json"),
            ReadResource("Currency.Reference.Iso4217.Generators.Content.list-replacement-currency-names.json"),
            ReadResource("Currency.Reference.Iso4217.Generators.Content.list-historical-currencies.json")
        );
    }

    protected static StringBuilder CreateSourceBuilder(string generatorName, string @namespace, string[]? references = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//     This file was generated by {generatorName}");
        sb.AppendLine("//     Do not modify this file manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        if (references is not null && references.Any())
        {
            foreach (var referenceName in references)
                sb.AppendLine($"using {referenceName};");
        }
        sb.AppendLine($"namespace {@namespace}");
        sb.AppendLine("{");
        return sb;
    }
}