using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Currency.Reference.Iso4217.Generators;

[Generator]
public class CurrencyEnumGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            try
            {
                var codes = new[]
                {
                    "USD", "EUR", "GBP", "JPY", "CHF", "CNY", "AUD", "CAD", "RUB"
                };

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("namespace Currency.Reference.Iso4217.Models");
                sb.AppendLine("{");
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    /// ISO 4217 currency codes enum.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public enum CurrencyCode");
                sb.AppendLine("    {");

                foreach (var code in codes.Distinct().OrderBy(c => c))
                {
                    sb.AppendLine($"        {code},");
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                ctx.AddSource("CurrencyCodeEnum.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
            catch (Exception ex)
            {
                var errorBuilder = new StringBuilder();
                errorBuilder.AppendLine("// <auto-generated />");
                errorBuilder.AppendLine("/*" +
                                        ex.GetType().Name + ": " + ex.Message + " " +
                                        "*/ ");
                ctx.AddSource("CurrencyCodeEnum.g.cs", SourceText.From(errorBuilder.ToString(), Encoding.UTF8));
            }
        });
    }
}