using System.Reflection;
using System.Text;
using Currency.Reference.Iso4217.Generators.Handlers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Currency.Reference.Iso4217.Generators;

[Generator]
public class CurrencyEnumGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(spc =>
        {
            try
            {
                var assembly = Assembly.GetExecutingAssembly();
                var resourceName = "Currency.Reference.Iso4217.Generators.Source.list-one-original-names.json";

                using var stream = assembly.GetManifestResourceStream(resourceName)
                                   ?? throw new InvalidOperationException("Embedded resource not found.");
                using var reader = new StreamReader(stream, Encoding.UTF8);
                var json = reader.ReadToEnd();

                var loader = new CurrencyLoader(json);
                var currencies = loader.Currencies;

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated>");
                sb.AppendLine("//   This file was generated by Currency.Reference.Iso4217.Generators source generator.");
                sb.AppendLine("//   Do not modify this file manually.");
                sb.AppendLine("// </auto-generated>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("namespace Currency.Reference.Iso4217;");
                sb.AppendLine("public enum CurrencyCode");
                sb.AppendLine("{");
                foreach (var c in currencies)
                {
                    sb.AppendLine($"    {c.Code}, // {c.Name}");
                }

                sb.AppendLine("}");

                spc.AddSource("CurrencyCode.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
            catch (Exception ex)
            {
                /*
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "CURRENCY001",
                        "Generator error",
                        $"Exception: {ex.Message}",
                        "CurrencyGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None));
                    */
            }
        });
    }
}