using System.Reflection;
using System.Text;
using Currency.Reference.Iso4217.Generators.Handlers;
using Currency.Reference.Iso4217.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
namespace Currency.Reference.Iso4217.Generators;

[Generator]
public class CurrencyCodeGenerator : BaseIncrementalGenerator
{
    public override string HintName => "CurrencyCode.g.cs";

    private const string StubSource = """
                                      // <auto-generated>
                                      //     This file was generated by Currency.Reference.Iso4217.Generators source generator.
                                      //     Do not modify this file manually.
                                      // </auto-generated>
                                      #nullable enable
                                      namespace Currency.Reference.Iso4217
                                      {
                                          ///<summary>Currency codes ISO4217</summary>
                                          public enum CurrencyCode
                                          {
                                              <summary> Unknown currency code </summary>
                                              None,
                                          }
                                      }
                                      """;

    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ErrorFactory.Clear();
        
        var jsonProvider = context.CompilationProvider.Select((_, _) =>
        {
            try
            {
                var assembly = Assembly.GetExecutingAssembly();
                const string originalResource =
                    "Currency.Reference.Iso4217.Generators.Data.list-original-currencies.json";
                using var originalStream = assembly.GetManifestResourceStream(originalResource)
                                           ?? throw new InvalidOperationException("Original JSON resource not found.");
                using var originalReader = new StreamReader(originalStream, Encoding.UTF8);
                var originalJson = originalReader.ReadToEnd();
                const string replacementResource =
                    "Currency.Reference.Iso4217.Generators.Data.list-replacement-currency-names.json";
                using var replacementStream = assembly.GetManifestResourceStream(replacementResource)
                                              ?? throw new InvalidOperationException(
                                                  "Replacement JSON resource not found.");
                using var replacementReader = new StreamReader(replacementStream, Encoding.UTF8);
                var replacementJson = replacementReader.ReadToEnd();
                return (OriginalJson: originalJson, ReplacementJson: replacementJson);
            }
            catch (Exception ex)
            {
                return (OriginalJson: $"__ERROR__:{ex.Message}", ReplacementJson: $"__ERROR__:{ex.Message}");
            }
        });
        context.RegisterSourceOutput(jsonProvider, (spc, jsonTuple) =>
        {
            try
            {
                var (originalJson, replacementJson) = jsonTuple;
                if (originalJson.StartsWith("__ERROR__"))
                {
                    ErrorFactory.Create(new ErrorDescription()
                    {
                        DiagnosticDescriptor = new DiagnosticDescriptor(
                            id: "CURRENCY001",
                            title: "Generator error",
                            messageFormat: $"Failed to load original resource: {originalJson.Substring(9)}",
                            category: string.Empty,
                            defaultSeverity: DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        GeneratorType = GeneratorType.Currency
                    });
                }

                if (replacementJson.StartsWith("__ERROR__"))
                {
                    ErrorFactory.Create(new ErrorDescription()
                    {
                        DiagnosticDescriptor = new DiagnosticDescriptor(
                            id: "CURRENCY002",
                            title: "Generator error",
                            messageFormat: $"Failed to load original resource: {replacementJson.Substring(9)}",
                            category: string.Empty,
                            defaultSeverity: DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        GeneratorType = GeneratorType.Currency
                    });
                }

                if (ErrorFactory.IsExists())
                {
                    ShowIssues(spc, GeneratorType.Currency);
                    spc.AddSource(HintName, SourceText.From(StubSource, Encoding.UTF8));
                    return;
                }

                var loader = new CurrencyLoader(originalJson, replacementJson);
                var currencies = loader.Currencies;

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated>");
                sb.AppendLine(
                    "//   This file was generated by Currency.Reference.Iso4217.Generators source generator.");
                sb.AppendLine("//   Do not modify this file manually.");
                sb.AppendLine("// </auto-generated>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("namespace Currency.Reference.Iso4217");
                sb.AppendLine("{");
                sb.AppendLine("    ///<summary>Currency codes ISO4217</summary>");
                sb.AppendLine("    public enum CurrencyCode");
                sb.AppendLine("    {");
                sb.AppendLine(
                    "        ///<summary> Unknown currency code </summary>");
                sb.AppendLine(
                    "        None,");
                foreach (var c in currencies)
                {
                    sb.AppendLine(
                        $"        ///<summary> {c.Name} </summary>");
                    sb.AppendLine(
                        $"        {c.Code},");
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");
                spc.AddSource(HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
            }
            catch (Exception ex)
            {
                ErrorFactory.Create(new ErrorDescription()
                {
                    DiagnosticDescriptor = new DiagnosticDescriptor(
                        id: "CURRENCY003",
                        title: "Generator error",
                        messageFormat: $"Unexpected exception: {ex.Message}",
                        category: string.Empty,
                        defaultSeverity: DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    GeneratorType = GeneratorType.Currency
                });
                if (ErrorFactory.IsExists())
                {
                    ShowIssues(spc, GeneratorType.Currency);
                    spc.AddSource(HintName, SourceText.From(StubSource, Encoding.UTF8));
                }
            }
        });
    }
}