using System.Reflection;
using System.Text;
using Currency.Reference.Iso4217.Generators.Handlers;
using Currency.Reference.Iso4217.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Currency.Reference.Iso4217.Generators;

[Generator]
public class CurrencyEnumGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonProvider = context.CompilationProvider.Select((_, _) =>
        {
            try
            {
                var assembly = Assembly.GetExecutingAssembly();
                const string resourceName = "Currency.Reference.Iso4217.Generators.Sources.list-one-original-names.json";
                using var stream = assembly.GetManifestResourceStream(resourceName)
                                   ?? throw new InvalidOperationException("Embedded resource not found.");
                using var reader = new StreamReader(stream, Encoding.UTF8);
                return reader.ReadToEnd();
            }
            catch (Exception ex)
            {
                return $"__ERROR__:{ex.Message}";
            }
        });
        context.RegisterSourceOutput(jsonProvider, (spc, jsonContent) =>
        {
            try
            {
                if (jsonContent is null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "CURRENCY001",
                            "Generator error",
                            "No JSON content loaded.",
                            "CurrencyGenerator",
                            DiagnosticSeverity.Error,
                            true),
                        Location.None));
                    return;
                }

                if (jsonContent.StartsWith("__ERROR__"))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "CURRENCY002",
                            "Generator error",
                            $"Failed to load resource: {jsonContent.Substring(9)}",
                            "CurrencyGenerator",
                            DiagnosticSeverity.Error,
                            true),
                        Location.None));
                    return;
                }

                var loader = new CurrencyLoader(jsonContent);
                var currencies = loader.Currencies;

                var sb1 = new StringBuilder();
                sb1.AppendLine("// <auto-generated>");
                sb1.AppendLine(
                    "//   This file was generated by Currency.Reference.Iso4217.Generators source generator.");
                sb1.AppendLine("//   Do not modify this file manually.");
                sb1.AppendLine("// </auto-generated>");
                sb1.AppendLine("#nullable enable");
                sb1.AppendLine("using System.Collections.Generic;");
                sb1.AppendLine("using Currency.Reference.Iso4217.Common.Models;");
                sb1.AppendLine("namespace Currency.Reference.Iso4217");
                sb1.AppendLine("{");
                sb1.AppendLine("    internal static class LocalDatabase");
                sb1.AppendLine("    {");
                sb1.AppendLine(
                    "        public static readonly IReadOnlyList<CurrencyInfo> Currencies = new List<CurrencyInfo>()");
                sb1.AppendLine("        {");
                foreach (var c in currencies)
                {
                    var currencyType = c.CurrencyType is not CurrencyType.Fiat
                        ? $", CurrencyType.{c.CurrencyType}"
                        : string.Empty;
                    sb1.AppendLine(
                        $"            new(\"{c.Code}\", \"{c.Name}\", \"{c.Country}\", \"{c.NumericCode}\"{currencyType}),");
                }

                sb1.AppendLine("        };");
                sb1.AppendLine("    };");
                sb1.AppendLine("}");
                spc.AddSource("LocalDatabase.g.cs", SourceText.From(sb1.ToString(), Encoding.UTF8));

                var sb2 = new StringBuilder();
                sb2.AppendLine("// <auto-generated>");
                sb2.AppendLine(
                    "//   This file was generated by Currency.Reference.Iso4217.Generators source generator.");
                sb2.AppendLine("//   Do not modify this file manually.");
                sb2.AppendLine("// </auto-generated>");
                sb2.AppendLine("#nullable enable");
                sb2.AppendLine("namespace Currency.Reference.Iso4217");
                sb2.AppendLine("{");
                sb2.AppendLine("    public enum CurrencyCode");
                sb2.AppendLine("    {");
                foreach (var c in currencies)
                {
                    sb2.AppendLine(
                        $"        {c.Code}, // {c.Name}");
                }
                sb2.AppendLine("    };");
                sb2.AppendLine("}");
                spc.AddSource("CurrencyCode.g.cs", SourceText.From(sb2.ToString(), Encoding.UTF8));
            }
            catch (Exception ex)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "CURRENCY003",
                        "Generator error",
                        $"Unexpected exception: {ex.Message}",
                        "CurrencyGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None));
            }
        });
    }
}