using System.Reflection;
using System.Text;
using Currency.Reference.Iso4217.Generators.Handlers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
namespace Currency.Reference.Iso4217.Generators;

[Generator]
public class CurrencyCodeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonProvider = context.CompilationProvider.Select((_, _) =>
        {
            try
            {
                var assembly = Assembly.GetExecutingAssembly();
                const string resourceName = "Currency.Reference.Iso4217.Generators.Data.list-original-currency-names.json";
                using var stream = assembly.GetManifestResourceStream(resourceName)
                                   ?? throw new InvalidOperationException("Embedded resource not found.");
                using var reader = new StreamReader(stream, Encoding.UTF8);
                return reader.ReadToEnd();
            }
            catch (Exception ex)
            {
                return $"__ERROR__:{ex.Message}"; 
            }
        });
        context.RegisterSourceOutput(jsonProvider, (spc, jsonContent) =>
        {
            try
            {
                if (jsonContent is null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "CURRENCY0011",
                            "Generator error",
                            "No JSON content loaded.",
                            "CurrencyGenerator",
                            DiagnosticSeverity.Error,
                            true),
                        Location.None));
                    return;
                }

                if (jsonContent.StartsWith("__ERROR__"))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "CURRENCY0021",
                            "Generator error",
                            $"Failed to load resource: {jsonContent.Substring(9)}",
                            "CurrencyGenerator",
                            DiagnosticSeverity.Error,
                            true),
                        Location.None));
                    return;
                }

                var loader = new CurrencyLoader(jsonContent);
                var currencies = loader.Currencies;
                
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated>");
                sb.AppendLine(
                    "//   This file was generated by Currency.Reference.Iso4217.Generators source generator.");
                sb.AppendLine("//   Do not modify this file manually.");
                sb.AppendLine("// </auto-generated>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("namespace Currency.Reference.Iso4217");
                sb.AppendLine("{");
                sb.AppendLine("    public enum CurrencyCode");
                sb.AppendLine("    {");
                
                sb.AppendLine(
                    "        ///<summary> Unknown currency code </summary>");
                sb.AppendLine(
                    "        None,");
                
                foreach (var c in currencies)
                {
                    sb.AppendLine(
                        $"        ///<summary> {c.Name} </summary>");
                    sb.AppendLine(
                        $"        {c.Code},");
                }
                sb.AppendLine("    }");
                sb.AppendLine("}");
                spc.AddSource("CurrencyCode.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
            catch (Exception ex)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "CURRENCY003",
                        "Generator error",
                        $"Unexpected exception: {ex.Message}",
                        "CurrencyGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None));
            }
        });
    }
}