using System.Reflection;
using System.Text;
using Currency.Reference.Iso4217.Generators.Handlers;
using Currency.Reference.Iso4217.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
namespace Currency.Reference.Iso4217.Generators;

[Generator]
public class CurrencyCodeGenerator : BaseIncrementalGenerator
{
    public override string HintName => "CurrencyCode.g.cs";

    private const string StubSource = """
                                      // <auto-generated>
                                      //    This file was generated by Currency.Reference.Iso4217.Generators source generator.
                                      //    Do not modify this file manually.
                                      // </auto-generated>
                                      #nullable enable
                                      namespace Currency.Reference.Iso4217
                                      {
                                          /// <summary> Currency codes ISO4217 </summary>
                                          public enum CurrencyCode
                                          {
                                              /// <summary> Unknown currency code </summary>
                                              None,
                                          }
                                      }
                                      """;

    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ErrorFactory.Clear();
        var jsonProvider = context.CompilationProvider.Select((_, _) =>
        {
            try
            {
                return LoadJsonResources(Assembly.GetExecutingAssembly());
            }
            catch (Exception ex)
            {
                return ($"{ErrorMark}:{ex.Message}", $"{ErrorMark}:{ex.Message}", $"{ErrorMark}:{ex.Message}");
            }
        });
        context.RegisterSourceOutput(jsonProvider, (spc, tuple) =>
        {
            try
            {
                var (originalJson, replacementJson, historicalJson) = tuple;

                if (originalJson.StartsWith(ErrorMark) || replacementJson.StartsWith(ErrorMark) ||
                    historicalJson.StartsWith(ErrorMark))
                {
                    if (originalJson.StartsWith(ErrorMark))
                        ErrorFactory.Create(new ErrorDescription
                        {
                            DiagnosticDescriptor = new DiagnosticDescriptor(
                                id: DiagnosticDescriptors.ResourceLoadErrorId,
                                title: DiagnosticsTitle,
                                messageFormat: $"Failed to load original resource: {originalJson.Substring(9)}",
                                category: string.Empty,
                                defaultSeverity: DiagnosticSeverity.Error,
                                isEnabledByDefault: true),
                            GeneratorType = GeneratorType.Currency
                        });
                    if (replacementJson.StartsWith(ErrorMark))
                        ErrorFactory.Create(
                            new ErrorDescription
                            {
                                DiagnosticDescriptor = new DiagnosticDescriptor(
                                    id: DiagnosticDescriptors.ResourceLoadErrorId,
                                    title: DiagnosticsTitle,
                                    messageFormat: $"Failed to load historical resource: {historicalJson.Substring(9)}",
                                    category: string.Empty,
                                    defaultSeverity: DiagnosticSeverity.Error,
                                    isEnabledByDefault: true),
                                GeneratorType = GeneratorType.Currency
                            });
                    if (historicalJson.StartsWith(ErrorMark))
                        ErrorFactory.Create(
                            new ErrorDescription
                            {
                                DiagnosticDescriptor = new DiagnosticDescriptor(
                                    id: DiagnosticDescriptors.ResourceLoadErrorId,
                                    title: DiagnosticsTitle,
                                    messageFormat:
                                    $"Failed to load replacement's resource: {historicalJson.Substring(9)}",
                                    category: string.Empty,
                                    defaultSeverity: DiagnosticSeverity.Error,
                                    isEnabledByDefault: true),
                                GeneratorType = GeneratorType.Currency
                            });
                    AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Currency);
                    return;
                }

                var loader = new CurrencyLoader(originalJson, replacementJson, historicalJson);
                var sb = CreateSourceBuilder(GeneratorName, DefaultNamespace);
                sb.AppendLine("    /// <summary> Currency codes ISO4217 </summary>")
                    .AppendLine("    public enum CurrencyCode")
                    .AppendLine("    {")
                    .AppendLine("        /// <summary> Unknown currency code </summary>")
                    .AppendLine("        None,");
                foreach (var c in loader.Currencies)
                {
                    sb.AppendLine($"        /// <summary> {c.Name} </summary>");
                    if (c.IsHistoric && !string.IsNullOrEmpty(c.WithdrawalDate))
                        sb.AppendLine($"        [Obsolete(\"Currency withdrawn on {c.WithdrawalDate}\")]");
                    sb.AppendLine($"        {c.Code},");
                }

                sb.AppendLine("    }")
                    .AppendLine("}");
                spc.AddSource(HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
            }
            catch (Exception ex)
            {
                ErrorFactory.Create(new ErrorDescription()
                {
                    DiagnosticDescriptor = new DiagnosticDescriptor(
                        id: DiagnosticDescriptors.UnexpectedErrorId,
                        title: DiagnosticsTitle,
                        messageFormat: $"Unexpected exception: {ex.Message}",
                        category: string.Empty,
                        defaultSeverity: DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    GeneratorType = GeneratorType.Currency
                });
                AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Currency);
            }
        });
    }
}