using System.Reflection;
using System.Text;
using Currency.Reference.Iso4217.Generators.Handlers;
using Currency.Reference.Iso4217.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
namespace Currency.Reference.Iso4217.Generators;

[Generator]
public class LocalDatabaseGenerator : BaseIncrementalGenerator
{
    public override string HintName => "LocalDatabase.g.cs";

    private const string StubSource = """
                                      // <auto-generated>
                                      //     This file was generated by Currency.Reference.Iso4217.Generators source generator.
                                      //     Do not modify this file manually.
                                      // </auto-generated>
                                      #nullable enable
                                      using System.Collections.Generic;
                                      using Currency.Reference.Iso4217.Domain.Entities;
                                      namespace Currency.Reference.Iso4217.Data
                                      {
                                          internal static class LocalDatabase
                                          {
                                              public static readonly IReadOnlyList<CurrencyInfo> Currencies = new List<CurrencyInfo>();
                                          }
                                      }
                                      """;
    
    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ErrorFactory.Clear();
        
        var jsonProvider = context.CompilationProvider.Select((_, _) =>
        {
            try
            {
                var assembly = Assembly.GetExecutingAssembly();
                const string originalResource =
                    "Currency.Reference.Iso4217.Generators.Data.list-original-currencies.json";
                using var originalStream = assembly.GetManifestResourceStream(originalResource)
                                           ?? throw new InvalidOperationException("Original JSON resource not found.");
                using var originalReader = new StreamReader(originalStream, Encoding.UTF8);
                var originalJson = originalReader.ReadToEnd();
                
                const string replacementResource =
                    "Currency.Reference.Iso4217.Generators.Data.list-replacement-currency-names.json";
                using var replacementStream = assembly.GetManifestResourceStream(replacementResource)
                                              ?? throw new InvalidOperationException(
                                                  "Replacement JSON resource not found.");
                using var replacementReader = new StreamReader(replacementStream, Encoding.UTF8);
                var replacementJson = replacementReader.ReadToEnd();
                
                const string historicalResource =
                    "Currency.Reference.Iso4217.Generators.Data.list-historical-currencies.json";
                using var historicalStream = assembly.GetManifestResourceStream(historicalResource)
                                             ?? throw new InvalidOperationException(
                                                 "Historical JSON resource not found.");
                using var historicalReader = new StreamReader(historicalStream, Encoding.UTF8);
                var historicalJson = historicalReader.ReadToEnd();
                
                return (OriginalJson: originalJson, ReplacementJson: replacementJson, HistoricalJson: historicalJson);
            }
            catch (Exception ex)
            {
                return (OriginalJson: $"__ERROR__:{ex.Message}", ReplacementJson: $"__ERROR__:{ex.Message}", HistoricalJson: $"__ERROR__:{ex.Message}");
            }
        });
        context.RegisterSourceOutput(jsonProvider, (spc, jsonTuple) =>
        {
            try
            {
                var (originalJson, replacementJson, historicalJson) = jsonTuple;
                if (originalJson.StartsWith("__ERROR__"))
                {
                    ErrorFactory.Create(new ErrorDescription()
                    {
                        DiagnosticDescriptor = new DiagnosticDescriptor(
                            id: "CURRENCY001",
                            title: "Generator error",
                            messageFormat: $"Failed to load original resource: {originalJson.Substring(9)}",
                            category: string.Empty,
                            defaultSeverity: DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        GeneratorType = GeneratorType.Database
                    });
                }
                if (replacementJson.StartsWith("__ERROR__"))
                {
                    ErrorFactory.Create(new ErrorDescription()
                    {
                        DiagnosticDescriptor = new DiagnosticDescriptor(
                            id: "CURRENCY002",
                            title: "Generator error",
                            messageFormat: $"Failed to load original resource: {replacementJson.Substring(9)}",
                            category: string.Empty,
                            defaultSeverity: DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        GeneratorType = GeneratorType.Database
                    });
                }
                if (historicalJson.StartsWith("__ERROR__"))
                {
                    ErrorFactory.Create(new ErrorDescription()
                    {
                        DiagnosticDescriptor = new DiagnosticDescriptor(
                            id: "CURRENCY002",
                            title: "Generator error",
                            messageFormat: $"Failed to load historical resource: {historicalJson.Substring(9)}",
                            category: string.Empty,
                            defaultSeverity: DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        GeneratorType = GeneratorType.Database
                    });
                }

                if (ErrorFactory.IsExists())
                {
                    ShowIssues(spc, GeneratorType.Database);
                    spc.AddSource(HintName, SourceText.From(StubSource, Encoding.UTF8));
                    return;
                }

                var loader = new CurrencyLoader(originalJson, replacementJson, historicalJson);
                var currencies = loader.Currencies;
                var historicalCurrencies = loader.HistoricalCurrencies;

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated>");
                sb.AppendLine(
                    "//   This file was generated by Currency.Reference.Iso4217.Generators source generator.");
                sb.AppendLine("//   Do not modify this file manually.");
                sb.AppendLine("// </auto-generated>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using Currency.Reference.Iso4217.Domain.Entities;");
                sb.AppendLine("namespace Currency.Reference.Iso4217.Data");
                sb.AppendLine("{");
                sb.AppendLine("    ///<summary>Currency information for codes ISO4217</summary>");
                sb.AppendLine("    internal static class LocalDatabase");
                sb.AppendLine("    {");
                sb.AppendLine(
                    "        public static readonly IReadOnlyList<Domain.Entities.Currency> ActualCurrencies = new List<Domain.Entities.Currency>()");
                sb.AppendLine("        {");
                foreach (var c in currencies)
                {
                    var currencyType = c.CurrencyType is not CurrencyType.Fiat
                        ? $", CurrencyType.{c.CurrencyType}"
                        : string.Empty;
                    var isHistorical = c.IsHistoric ? "true" : "false";
                    sb.AppendLine(
                        $"            new(\"{c.Code}\", \"{c.Name}\", \"{c.Country}\", \"{c.NumericCode}\", {isHistorical}, {ParseWithdrawalDate(c.WithdrawalDate)}{currencyType}),");
                }
                sb.AppendLine("        };");
                
                sb.AppendLine(
                    "        ///<summary>Currency historical information for codes ISO4217</summary>");              
                sb.AppendLine(
                    "        public static readonly IReadOnlyList<Domain.Entities.Currency> HistoricalCurrencies = new List<Domain.Entities.Currency>()");
                sb.AppendLine("        {");
                foreach (var c in historicalCurrencies)
                {
                    var currencyType = c.CurrencyType is not CurrencyType.Fiat
                        ? $", CurrencyType.{c.CurrencyType}"
                        : string.Empty;
                    var isHistorical = c.IsHistoric ? "true" : "false";
                    sb.AppendLine(
                        $"            new(\"{c.Code}\", \"{c.Name}\", \"{c.Country}\", \"{c.NumericCode}\", {isHistorical}, {ParseWithdrawalDate(c.WithdrawalDate)}{currencyType}),");
                }

                sb.AppendLine("        };");
                sb.AppendLine("    };");
                
                sb.AppendLine("}");
                spc.AddSource(HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
            }
            catch (Exception ex)
            {
                ErrorFactory.Create(new ErrorDescription()
                {
                    DiagnosticDescriptor = new DiagnosticDescriptor(
                        id: "CURRENCY004",
                        title: "Generator error",
                        messageFormat: $"Unexpected exception: {ex.Message}",
                        category: string.Empty,
                        defaultSeverity: DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    GeneratorType = GeneratorType.Database
                });
                if (ErrorFactory.IsExists())
                {
                    ShowIssues(spc, GeneratorType.Database);
                    spc.AddSource(HintName, SourceText.From(StubSource, Encoding.UTF8));
                }
            }
        });
    }
    
    private static string? ParseWithdrawalDate(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return " null";
        return DateTime.TryParseExact(raw, "yyyy-MM", null, System.Globalization.DateTimeStyles.None, out var dt) ? $" new DateOnly({dt.Year}, {dt.Month}, 1)" : " null";
    }
}